[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lcatoolbox"
version = "0.1.0"
authors = [{name = "Jonathan Larochelle", email = "jonathan.larochelle@h-ka.de"}, ]
description = "(...)"
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "brightway25",
    "numpy",
]
license = {file = "LICENSE"}

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "pytest-mock",]

[tool.setuptools.packages.find]
include = ["lcatoolbox*"]

[project.urls]
Homepage = "https://github.com/HKA-IES/lca_toolbox"
Issues = "https://github.com/HKA-IES/lca_toolbox/issues"